name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }} \
                        -d ${{ secrets.POSTGRES_DB }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run tests
        env:
          DATABASE_URL: >-
            postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}
            @localhost:5432/${{ secrets.POSTGRES_DB }}?sslmode=disable
        run: |
          until pg_isready -h localhost -p 5432 \
            -U "${{ secrets.POSTGRES_USER }}" \
            -d "${{ secrets.POSTGRES_DB }}"; do
            echo "Waiting for Postgres..."
            sleep 2
          done
          go test ./... -timeout 60s -v